### ISSUE TITLE
Not working on Android Q+

### ISSUE THREAD

**Issue by robertlevonyan** [bmc08gt/scrcast#46]
The file of recording is not being saved on Android Q+ (I think the library doesn't have a Scoped storage support)

**Comment by robertlevonyan** [comment]
Also on lower versions the file is not playable

**Comment by miroslavkovac** [comment]
Looks like the file is not ready at the time `onRecordingComplete` is called, but only after the Activity is terminated. When I compare the two files, it appears as if something extra is written to the file header later and that makes the file readable. I didn't fine any way of causing the file to be finalized by the time `onRecordingComplete` is called.

Any ideas on how to solve this? Thanks

**Comment by way2jatin** [comment]
@miroslavkovac Even i had the same issue as mentioned in the link below --> https://github.com/bmcreations/scrcast/issues/39#issuecomment-750341070 . Any update on how to fix this as when i try to share the same file, the video is not playable then. 😄

**Comment by bmc08gt** [comment]
0.3.0 is being deployed now; please check maven in a few hours for the fixes.
