### ISSUE TITLE
Question: is it a good solution to capture only the current app's content?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [bmc08gt/scrcast#50]
Suppose I want to capture only what's on my app, is this still the only solution that I can use, using the special permission?
Or is there a better one?

And what if I want to capture what's on my app, but including when it shows the OS background (static or live wallpaper) behind ?

**Comment by bmc08gt** [comment]
This library will allow you to integrate full device screen recording into an existing or new app. That includes all app content and system level screens.

**Comment by bmc08gt** [comment]
> This library will allow you to integrate full device screen recording into an existing or new app. That includes all app content and system level screens.

With that being said, there is an option to end screen recording on screen off https://bmcreations.github.io/scrcast/api/library/dev.bmcreations.scrcast.config/-options/stop-on-screen-off/. 

I can add an option to pause/resume wrt app lifecycle

**Comment by AndroidDeveloperLB** [comment]
Oh so it's global and not just of the app... Right?

**Comment by bmc08gt** [comment]
> Oh so it's global and not just of the app... Right?

Correct. It utilizes platform APIs to record the entire screen content.

**Comment by AndroidDeveloperLB** [comment]
@bmc08gt I see. 
Do you know perhaps if it's possible to capture just the current app, without this special permission ?

**Comment by bmc08gt** [comment]
> @bmc08gt I see. 
> 
> Do you know perhaps if it's possible to capture just the current app, without this special permission ?
> 
> 

Which permission are you referring to?

**Comment by AndroidDeveloperLB** [comment]
@bmc08gt I don't know how it's called, but it's what you get when you start recording. It asks you if it's ok to let the app record the screen.

**Comment by bmc08gt** [comment]
> @bmc08gt I don't know how it's called, but it's what you get when you start recording. It asks you if it's ok to let the app record the screen.

Unfortunately there is no way around that request. It's tied to the MediaProjection APIs.

**Comment by AndroidDeveloperLB** [comment]
@bmc08gt So without MediaProjection , I can't take a video of my own app?
What about images? This is possible?

**Comment by bmc08gt** [comment]
> @bmc08gt So without MediaProjection , I can't take a video of my own app?
> 
> What about images? This is possible?

Screenshots are possible without media projection. Window provides the drawing cache or you can utilize canvas to save the result into a bitmap.

**Comment by AndroidDeveloperLB** [comment]
@bmc08gt This won't work though if you have an Activity that shows the current wallpaper though, right?
BTW, I think there is a better solution nowadays instead of drawing cache.

**Comment by bmc08gt** [comment]
> @bmc08gt This won't work though if you have an Activity that shows the current wallpaper though, right?
> 
> BTW, I think there is a better solution nowadays instead of drawing cache.

Those were two examples but yes there is.

**Comment by AndroidDeveloperLB** [comment]
@bmc08gt Two examples?
