### ISSUE TITLE
mediaStorageLocation is overwritten/not used for storing videos

### ISSUE THREAD

**Issue by hillcormac** [bmc08gt/scrcast#55]
**Bug**
I set the directory, directoryName, and fileNameFormatter I want in the object options. The fileNameFormatter specified is used, but the video is not saved to the correct directory.

**Expected behaviour**
The video saves to the specified directory.

**Logs/Screenshots**
First line is the storage directory specified _(recorder.options.storage.mediaStorageLocation immediately after applying options to recorder)_.
Second line is the path to which the video file is actually saved _(file.absolutePath in onRecordingFinished callback)._
![image](https://user-images.githubusercontent.com/44039816/126484821-2e03bb8e-d815-47a3-beea-c15e9c902873.png)

**Version**
v0.3.0

**Note**
I'm relatively new to Android development, so it may be a simple mistake in my code rather than a bug.

**Comment by bmc08gt** [comment]
Yes this was fixed by #52 , I’ll work on getting 0.3.1 out this week.

**Comment by bmc08gt** [comment]
Closing this for now, but if it is still an issue after the next release we can reopen this.

**Comment by hillcormac** [comment]
Apologies, didn't see that this issue had already been flagged. Thanks for the update.

**Comment by bmc08gt** [comment]
> Apologies, didn't see that this issue had already been flagged. Thanks for the update.

No worries! I appreciate you reporting it.

**Comment by hillcormac** [comment]
Pinging this issue again to see if there's any update on a new release coming soon?
